AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for OnnxSentiAnaLight

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 2048

Resources:
  SentiAnalysisFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        SentiAnalysis:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /senti-analysis
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./senti_analysis
      DockerTag: python3.9-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SentiAnalysisApi:
    Description: "API Gateway endpoint URL for Prod stage for Senti Analysis function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/senti-analysis/"
  SentiAnalysisFunction:
    Description: "Senti Analysis Lambda Function ARN"
    Value: !GetAtt SentiAnalysisFunction.Arn
  SentiAnalysisFunctionIamRole:
    Description: "Implicit IAM Role created for Senti Analysis function"
    Value: !GetAtt SentiAnalysisFunctionRole.Arn
